### ISSUE TITLE
build error on ubuntu: An unstable feature was used

### ISSUE THREAD

**Issue by mdrenger** [ogham/dog#10]
dog fails to compile due to https://github.com/rust-lang/rust/issues/65721

- The exact dog commit you are building (`git rev-parse --short HEAD`)
git rev-parse --short HEAD
- The version of rustc you are compiling it with (`rustc --version`)
rustc 1.41.1 (f3e1a954d 2020-02-24)

- The Rust build target (the _exact_ output of `rustc --print cfg`)

Output:
---
cargo build
    Updating crates.io index
    Updating git repository `https://github.com/llogiq/mutagen`
  Downloaded log v0.4.11
  Downloaded rand v0.7.3
  Downloaded serde_json v1.0.59
  Downloaded byteorder v1.3.4
  Downloaded getopts v0.2.21
  Downloaded serde v1.0.117
  Downloaded native-tls v0.2.4
  Downloaded httparse v1.3.4
  Downloaded datetime v0.5.1
  Downloaded ansi_term v0.12.1
  Downloaded atty v0.2.14
  Downloaded regex v1.4.2
  Downloaded cfg-if v0.1.10
  Downloaded getrandom v0.1.15
  Downloaded openssl-probe v0.1.2
  Downloaded openssl v0.10.30
  Downloaded libc v0.2.80
  Downloaded rand_core v0.5.1
  Downloaded itoa v0.4.6
  Downloaded openssl-sys v0.9.58
  Downloaded ryu v1.0.5
  Downloaded rand_chacha v0.2.2
  Downloaded unicode-width v0.1.8
  Downloaded foreign-types v0.3.2
  Downloaded lazy_static v1.4.0
  Downloaded autocfg v1.0.1
  Downloaded cc v1.0.61
  Downloaded pkg-config v0.3.19
  Downloaded ppv-lite86 v0.2.10
  Downloaded bitflags v1.2.1
  Downloaded regex-syntax v0.6.21
  Downloaded foreign-types-shared v0.1.1
   Compiling libc v0.2.80
   Compiling cfg-if v0.1.10
   Compiling cc v1.0.61
   Compiling pkg-config v0.3.19
   Compiling autocfg v1.0.1
   Compiling bitflags v1.2.1
   Compiling log v0.4.11
   Compiling getrandom v0.1.15
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.30
   Compiling byteorder v1.3.4
   Compiling lazy_static v1.4.0
   Compiling httparse v1.3.4
   Compiling ryu v1.0.5
   Compiling regex-syntax v0.6.21
   Compiling native-tls v0.2.4
   Compiling serde v1.0.117
   Compiling serde_json v1.0.59
   Compiling openssl-probe v0.1.2
   Compiling ppv-lite86 v0.2.10
   Compiling unicode-width v0.1.8
   Compiling itoa v0.4.6
   Compiling ansi_term v0.12.1
   Compiling foreign-types v0.3.2
   Compiling getopts v0.2.21
   Compiling dns v0.1.0 (/opt/dog/dog/dns)
error[E0658]: use of unstable library feature 'matches_macro'
   --> dns/src/types.rs:217:9
    |
217 |         matches!(self, Self::Standard { .. })
    |         ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

   Compiling datetime v0.5.1
   Compiling atty v0.2.14
   Compiling openssl-sys v0.9.58
   Compiling rand_core v0.5.1
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `dns`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by ogham** [comment]
You'll need [Rust 1.45.0](https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html) or higher to build dog, because it uses a couple of features that were stabilised after 1.41.0 was released. (Your compiler is hitting `matches_macro`, which was stabilised in 1.42.0, but there are some other ones that it will hit after that).
