### ISSUE TITLE
brew formula is deprecated or disabled

### ISSUE THREAD

**Issue by hhemied** [ogham/dog#121]
The `brew doctor` command shows that the `dog` formula is deprecated or disabled
```
Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  dog
```
Any other formula to use or is a bug?

**Comment by evanleck** [comment]
Like https://github.com/ogham/exa I suspect this project is being considered unmaintained.

**Comment by luckman212** [comment]
Not sure if they have 100% feature parity, but https://github.com/mr-karan/doggo is still maintained and available via `brew install doggo`

**Comment by hhemied** [comment]
Then `dog` isn't maintainable anymore and `doggo` is the current active fork?
I removed `dog` and installed `doggo` instead.

**Comment by hhemied** [comment]
`doggo` isn't a fork.
It's built on `Go` and `dog` was built on `Rust`

**Comment by JayBrown** [comment]
Like `exa`, `dog` is still available via [**MacPorts**](https://www.macports.org/). In these cases I always uninstall the brew formula, and reinstall using `port`, unless there's a good substitute available via `brew`, which in this case there is with `doggo`.

**Comment by luckman212** [comment]
I never said doggo was a fork of dog. It's just a more actively maintained alternative.

**Comment by thezacharytaylor** [comment]
> Like https://github.com/ogham/exa I suspect this project is being considered unmaintained.

There is a fork of that, [eza](https://github.com/eza-community/eza).

**Comment by hhemied** [comment]
Thanks @luckman212 for your input (I didn't say you said that ;) )
Thanks @thezacharytaylor.
