### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by Trollwut** [ogham/dog#17]
hey, first of all, I like this approach! :) 

has everything I want from `dig`, but with an easier-to-read output.

Would you mind providing an AUR package (for Arch Linux)?

**Comment by ogham** [comment]
I have no idea how to do that. Fortunately I don't _have_ to, because someone already did! [Search the AUR for `dns-dog`](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=dog-dns&outdated=&SB=n&SO=a&PP=50&do_Search=Go).

**Comment by Trollwut** [comment]
Aaaah, I searched the AUR for "dig dog", so that's why I haven't found it. :D 

WIll tell the maintainer to include the "dig" word so other people can find it easier. Thanks for responding!
