### ISSUE TITLE
Malformed packet

### ISSUE THREAD

**Issue by beaugunderson** [ogham/dog#18]
Version: v0.1.0
OS & hardware: macOS 10.15.7, 2020 MacBook Pro 16"
Arguments: `dog TXT canvasmedical.com`

```
$ dog TXT canvasmedical.com
Error [protocol]: Malformed packet: length 105 was specified, but read 69 bytes
```

Works with `dig`.

**Comment by ogham** [comment]
I can reproduce this locally too. Wireshark also accepts the packet.

This is a bug in dog — the TXT record specification (I just looked this up) allows for multiple text fields per record, but dog stops parsing after one, then complains that it expected more. The solution will be to add a loop in the TXT record parser.

(Completely unrelated to this issue: there's something about [those numbers in particular](https://zork.fandom.com/wiki/69105) I couldn't help but notice...)

**Comment by ogham** [comment]
I made the change to the TXT parser, and that request now works for me:

![Screenshot 2020-11-10 at 00 06 51](https://user-images.githubusercontent.com/503760/98610897-a3280c80-22e8-11eb-974b-7f965efbb36c.png)
