### ISSUE TITLE
Support querying unknown types

### ISSUE THREAD

**Issue by dmcardle** [ogham/dog#20]
Cool project!

It would be great if the `--type` parameter enabled the user to query types that dog doesn't know about.

[RFC3597](https://tools.ietf.org/html/rfc3597) section 5 describes a conventional text representation for unknown (and optionally known) RR types:

```
   In the "type" field of a master file line, an unknown RR type is
   represented by the word "TYPE" immediately followed by the decimal RR
   type number, with no intervening whitespace.
```

For example, `--type=TYPE28` would be equivalent to `--type=AAAA`.

I'd contribute a patch, but unfortunately my hands are tied due to the license.

**Comment by ogham** [comment]
Thanks!

dog supports passing in numbers to the `--type` and `--class` options already:

![Screenshot 2020-11-10 at 19 02 54](https://user-images.githubusercontent.com/503760/98719183-58110680-2387-11eb-8582-58aa5f770403.png)

Uh, I may have added some text to a log file somewhere. Anyway, I believe that RFC is talking about the syntax for defining records on DNS _servers_, and as a client we're allowed to deviate from the presentation format sometimes.

> I'd contribute a patch, but unfortunately my hands are tied due to the license.

Could I ask why this is the case? I appreciate that EUPL-1.2 isn't one of the mainstream ones.

**Comment by dmcardle** [comment]
Aha, I must not have tried very hard, my bad.

> Anyway, I believe that RFC is talking about the syntax for defining records on DNS servers, and as a client we're allowed to deviate from the presentation format sometimes.

Yep, that's my understanding as well. I only brought it up because I thought you didn't have a syntax yet.

As for the license issue, Google allows employees to contribute to open-source projects as long as they have a license that allows for private use. Unfortunately that rules out AGPL and EUPL. https://opensource.google/docs/thirdparty/licenses/#european-union-public-licence-eupl-not-allowed

**Comment by ogham** [comment]
Interesting — thank you for pointing me to this page. I was aware of the AGPL's ramifications within large companies, but not that they would extend to installing or contributing to it.
