### ISSUE TITLE
error[E0658]: use of unstable library feature 'str_strip': newly added

### ISSUE THREAD

**Issue by bkzachariah** [ogham/dog#26]
- The exact dog commit you are building (`git rev-parse --short HEAD`)
- The version of rustc you are compiling it with (`rustc --version`) -  rustc 1.43.0 
- Your operating system and hardware platform -  Ubuntu 20.04
- The Rust build target (the _exact_ output of `rustc --print cfg`)

dog-0.1.0 Version 

If you are seeing compilation errors, please include the output of the build process.

   Compiling rand_core v0.5.1
   Compiling dog v0.1.0 (/home/ubuntu/dog-0.1.0)
   Compiling rand_chacha v0.2.2
   Compiling rand v0.7.3
   Compiling dns-transport v0.1.0 (/home/ubuntu/dog-0.1.0/dns-transport)
error[E0658]: use of unstable library feature 'str_strip': newly added
   --> dns-transport/src/https.rs:109:36
    |
109 |         if let Some(sp) = self.url.strip_prefix("https://") {
    |                                    ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `dns-transport`.

To learn more, run the command again with --verbose.

---

**Comment by pschmitt** [comment]
I've been there as well, on KDE Neon. You need to update your Rust install.
Uninstall `rustc` and `cargo`, then get a fresh version using [rustup](https://rustup.rs/).

**Comment by ogham** [comment]
That's correct — you need Rust v1.45.0 or higher, because dog uses features that were recently stabilised. rustup is indeed the best way to get this onto your system.
