### ISSUE TITLE
ANSI codes not working in Windows Powershell Window

### ISSUE THREAD

**Issue by iguyking** [ogham/dog#35]
Running dog on Windows 10 Pro with Powershell or Powershell Core window does not generate the color coding expected.  

Under the default Powershell terminal
![image](https://user-images.githubusercontent.com/5004028/99211028-f4267d80-278c-11eb-8a4a-4e1c8f3be943.png)

Under the Powershell Core 7.1 terminal
![image](https://user-images.githubusercontent.com/5004028/99211078-1d470e00-278d-11eb-9988-952dea350495.png)

- The version of dog being used (`dog --version`)
`v0.1.0`

- The command-line arguments you are using
`./dog.exe yahoo.com -n 8.8.8.8`

- Your operating system and hardware platform
```
Windows 10 Pro
Version 2004 (OS Build 19041.630)
```

Love the idea and want to use this. Thanks for building it and releasing it.

**Comment by iguyking** [comment]
It does work properly after more testing with the new Windows Terminal v1.4 running Powershell Core 7.1

![image](https://user-images.githubusercontent.com/5004028/99211296-9b0b1980-278d-11eb-8e13-58ef3ef59bf1.png)

**Comment by ogham** [comment]
This has been fixed in `master`; see #6. As you found out, I only tested it in Windows Terminal.
