### ISSUE TITLE
Introduce `openssl-vendored` or Consider using rustls (#21)

### ISSUE THREAD

**Issue by IceCodeNew** [ogham/dog#53]
As for now, it's quite challenging to cross-compile this project.
To let the users pass additional features like `openssl-vendored` would make it much more comfortable. However, I would also recommend switching to rustls (#21).

**Comment by ogham** [comment]
Continuing from #21: once dog gets pluggable SSL implementations, I'll make sure `openssl-vendored` is one of them. I'm going to leave this issue open as a reminder.
