### ISSUE TITLE
Issue with docs 

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [ogham/dog#58]
If dog does something unexpected, or displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- N/A
- -S vs -T
- N/A
- 
If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

The docs (specifically https://dns.lookup.dog/features/dns-over-tls) reference DoT being -T, but -T is for TCP, not TLS (TLS is -S) (tested to make sure, corroborated by other parts of the manual)

Sorry if this isn't the right place, I couldn't find the docs repository

**Comment by ogham** [comment]
Oh my goodness, I've seen that page a million times and never noticed. Thanks for spotting it! The fix is currently on its way up.
