### ISSUE TITLE
[Windows] Prints ANSI codes instead of colored text

### ISSUE THREAD

**Issue by gaeulbyul** [ogham/dog#6]
* dog version: 0.1.0 (Downloaded prebuilt binary from https://github.com/ogham/dog/releases/tag/v0.1.0 )
* OS: Windows 10 (Microsoft Windows [Version 10.0.19042.572])

Maybe need to call [enable_ansi_support](https://docs.rs/ansi_term/0.12.1/x86_64-pc-windows-msvc/ansi_term/fn.enable_ansi_support.html) function somewhere...?

![image](https://user-images.githubusercontent.com/830515/98546855-ac11e180-22da-11eb-9f1f-11811ee305d2.png)

**Comment by ogham** [comment]
I tested it on Windows Terminal which does ANSI codes, so I didn't notice this. Thanks for pointing it out

**Comment by SuperBartimus** [comment]
experiencing the same

**Comment by verydapeng** [comment]
happens inside powershell too

**Comment by theAkito** [comment]
Can confirm this issue for Powershell.

**Comment by ogham** [comment]
It's looking better now:

![win32](https://user-images.githubusercontent.com/503760/98714299-9f47c900-2380-11eb-9a70-ccef00fa5a83.png)

**Comment by user9931** [comment]
in case someout also find this from search... 

for some reason cant find setting in the gui but VirtualTerminalLevel = 1 in HKEY_CURRENT_USER\Console helps in windows 10, now the app shows color output with regular command prompt window. but this applies only for win 10 cause it using new console engine, and dont work in older version. in win 8.1/7/2012 the only way is to use other console like comemu to get colors...
